import { BreakerColor, BreakerFontSizes, BreakerIcon, BreakerSize } from '../enums/item.enum';

export const SWITCHER_SIZES_MAP: { [key: string]: BreakerSize } = {
  x1 : BreakerSize.ONE,
  x2 : BreakerSize.TWO,
  x3 : BreakerSize.THREE,
};

export const BREAKER_FONT_SIZES: BreakerFontSizes[] = [
  BreakerFontSizes.SIX,
  BreakerFontSizes.EIGHT,
  BreakerFontSizes.TEN,
  BreakerFontSizes.TWELVE,
  BreakerFontSizes.FOURTEEN,
  BreakerFontSizes.SIXTEEN,
  BreakerFontSizes.EIGHTEEN,
  BreakerFontSizes.TWENTY,
  BreakerFontSizes.TWENTY_TWO,
  BreakerFontSizes.TWENTY_FOUR,
  BreakerFontSizes.THIRTY_TWO,
  BreakerFontSizes.FORTY_EIGHT,
];

export const BREAKER_COLORS: BreakerColor[] = [
  BreakerColor.RED,
  BreakerColor.LIGHT_RED,
  BreakerColor.PINK,
  BreakerColor.DARK_PINK,
  BreakerColor.GREY,
  BreakerColor.DARK_GREEN,
  BreakerColor.GREEN,
  BreakerColor.LIGHT_GREEN,
  BreakerColor.SAND,
  BreakerColor.BROWN,
  BreakerColor.LIGHT_BROWN,
  BreakerColor.DARK_BLUE,
  BreakerColor.BLUE,
  BreakerColor.LIGHT_BLUE,
  BreakerColor.PURPLE,
];

export const BREAKER_ICONS: BreakerIcon[] = [
  BreakerIcon.HOME,
  BreakerIcon.BATHROOM,
  BreakerIcon.WASHING_MACHINE,
  BreakerIcon.DISHWASHER,
  BreakerIcon.SOCKETS,
  BreakerIcon.LAMP,
  BreakerIcon.LAMP_CIRCLE,
  BreakerIcon.LIGHT,
  BreakerIcon.BOLT,
  BreakerIcon.OFFLINE_BOLT,
  BreakerIcon.POWER,
  BreakerIcon.EV_STATION,
  BreakerIcon.HOUSE,
  BreakerIcon.MICROWAVE,
  BreakerIcon.KETTLE,
  BreakerIcon.OVEN_GEN,
  BreakerIcon.OVEN,
  BreakerIcon.GARAGE_HOME,
  BreakerIcon.GARAGE,
  BreakerIcon.DINING,
  BreakerIcon.HEAT_PUMP,
  BreakerIcon.BEDROOM_BABY,
  BreakerIcon.BEDROOM_PARENT,
  BreakerIcon.MODE_OFF_ON,
  BreakerIcon.LIVING,
  BreakerIcon.WATER_HEATER,
  BreakerIcon.AIR_PURIFIER_GEN,
  BreakerIcon.AIR_PURIFIER,
  BreakerIcon.COOKING,
  BreakerIcon.KITCHEN,
  BreakerIcon.AIRWARE,
  BreakerIcon.SWITCH,
  BreakerIcon.AC_UNIT,
  BreakerIcon.SKILLET_COOKTOP,
  BreakerIcon.MODE_FAN,
  BreakerIcon.GATE,
  BreakerIcon.SETTING_ALERT,
  BreakerIcon.LIGHT_GROUP,
  BreakerIcon.WALL_LAMP,
  BreakerIcon.EMOJI_OBJECT,
  BreakerIcon.WB_SUNNY,
];
