import { ITourStep } from '../../types/tour';
import { TourStepAnchorEnum } from '../enums/tour-steps.enum';
import { MdMenuPlacement } from 'ngx-ui-tour-md-menu';

const TOUR_WIDTH_SETTING: { minWidth: string, maxWidth: string } = { minWidth: '380px', maxWidth: '450px' };
const TOUR_POSITION_SETTING_BEFORE: MdMenuPlacement = { xPosition: 'before' };
const TOUR_POSITION_SETTING_TOP: MdMenuPlacement = { yPosition: 'above' };
const TOUR_SIDEBAR_ANIMATION_DELAY: number = 300;

export const TOUR_STEPS: ITourStep[] = [
  {
    anchorId: TourStepAnchorEnum.HEADER_LANGUAGE,
    content: 'USER_TOUR__HEADER_START',
    title: 'USER_TOUR__HEADER_START_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
  },
  {
    anchorId: TourStepAnchorEnum.HEADER_SETTINGS,
    content: 'USER_TOUR__HEADER_SETTINGS',
    title: 'USER_TOUR__HEADER_SETTINGS_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
  },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_TYPE,
    content: 'USER_TOUR__SETTINGS_TYPE',
    title: 'USER_TOUR__SETTINGS_TYPE_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
    delayBeforeStepShow: TOUR_SIDEBAR_ANIMATION_DELAY,
  },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_SIZE_TYPE,
    content: 'USER_TOUR__SETTINGS_SIZE_TYPE',
    title: 'USER_TOUR__SETTINGS_SIZE_TYPE_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
  },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_SIZE,
    content: 'USER_TOUR__SETTINGS_SIZE',
    title: 'USER_TOUR__SETTINGS_SIZE_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
  },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_BREAKER_QUANTITY,
    content: 'USER_TOUR__SETTINGS_BREAKER_QUANTITY',
    title: 'USER_TOUR__SETTINGS_BREAKER_QUANTITY_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
  },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_SEPERATED_UNITED,
    content: 'USER_TOUR__SETTINGS_SEPERATED_UNITED',
    title: 'USER_TOUR__SETTINGS_SEPERATED_UNITED_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
  },
  // {
  //   anchorId: TourStepAnchorEnum.SETTINGS_PRINT_ORIENTATION,
  //   content: 'USER_TOUR__SETTINGS_SIZE_TYPE',
  //   title: 'USER_TOUR__SETTINGS_SIZE_TYPE_TITLE',
  //   placement: TOUR_POSITION_SETTING_BEFORE,
  //   stepDimensions: TOUR_WIDTH_SETTING,
  //   nextOnAnchorClick: true,
  // },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_LABEL_SIZE,
    content: 'USER_TOUR__SETTINGS_LABEL_SIZE',
    title: 'USER_TOUR__SETTINGS_LABEL_SIZE_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
  },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_FONT,
    content: 'USER_TOUR__SETTINGS_FONT',
    title: 'USER_TOUR__SETTINGS_FONT_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
  },
  {
    anchorId: TourStepAnchorEnum.SETTINGS_SAVE,
    content: 'USER_TOUR__SETTINGS_SAVE',
    title: 'USER_TOUR__SETTINGS_SAVE_TITLE',
    placement: TOUR_POSITION_SETTING_BEFORE,
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
  },
  {
    anchorId: TourStepAnchorEnum.CONSTRUCTOR_RAIL,
    content: 'USER_TOUR__CONSTRUCTOR_RAIL',
    title: 'USER_TOUR__CONSTRUCTOR_RAIL_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    delayBeforeStepShow: TOUR_SIDEBAR_ANIMATION_DELAY,
  },
  {
    anchorId: TourStepAnchorEnum.ROW_EDIT_BREAKER,
    content: 'USER_TOUR__CONSTRUCTOR_EDIT_BREAKER',
    title: 'USER_TOUR__CONSTRUCTOR_EDIT_BREAKER_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
  },
  {
    anchorId: TourStepAnchorEnum.EDIT_BREAKER_DIALOG_INFO,
    content: 'USER_TOUR__EDIT_BREAKER_DIALOG_INFO',
    title: 'USER_TOUR__EDIT_BREAKER_DIALOG_INFO_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    placement: TOUR_POSITION_SETTING_BEFORE,
    isAsync: true,
  },
  {
    anchorId: TourStepAnchorEnum.EDIT_BREAKER_DIALOG_COLOR,
    content: 'USER_TOUR__EDIT_BREAKER_DIALOG_COLOR',
    title: 'USER_TOUR__EDIT_BREAKER_DIALOG_COLOR_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
    isAsync: true,
  },
  {
    anchorId: TourStepAnchorEnum.EDIT_BREAKER_DIALOG_ICON,
    content: 'USER_TOUR__EDIT_BREAKER_DIALOG_ICON',
    title: 'USER_TOUR__EDIT_BREAKER_DIALOG_ICON_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
    isAsync: true,
  },
  {
    anchorId: TourStepAnchorEnum.EDIT_BREAKER_DIALOG_ACTIONS,
    content: 'USER_TOUR__EDIT_BREAKER_DIALOG_ACTIONS',
    title: 'USER_TOUR__EDIT_BREAKER_DIALOG_ACTIONS_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
    isAsync: true,
    placement: TOUR_POSITION_SETTING_BEFORE,
  },
  {
    anchorId: TourStepAnchorEnum.ROW_DELETE_BREAKER,
    content: 'USER_TOUR__ROW_DELETE_BREAKER',
    title: 'USER_TOUR__ROW_DELETE_BREAKER_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    delayBeforeStepShow: TOUR_SIDEBAR_ANIMATION_DELAY,
    placement: TOUR_POSITION_SETTING_TOP,
    disableScrollToAnchor: true,
    nextOnAnchorClick: true,
  },
  {
    anchorId: TourStepAnchorEnum.CONSTRUCTOR_DELETE_ROW,
    content: 'USER_TOUR__CONSTRUCTOR_DELETE_ROW',
    title: 'USER_TOUR__CONSTRUCTOR_DELETE_ROW_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    delayBeforeStepShow: TOUR_SIDEBAR_ANIMATION_DELAY,
    placement: TOUR_POSITION_SETTING_TOP,
    isAsync: true,
    nextOnAnchorClick: true,
  },
  {
    anchorId: TourStepAnchorEnum.CONSTRUCTOR_ADD_RAIL,
    content: 'USER_TOUR__CONSTRUCTOR_ADD_RAIL',
    title: 'USER_TOUR__CONSTRUCTOR_ADD_RAIL_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    delayBeforeStepShow: TOUR_SIDEBAR_ANIMATION_DELAY,
    nextOnAnchorClick: true,
    disableScrollToAnchor: true,
  },
  {
    anchorId: TourStepAnchorEnum.HEADER_PREVIEW,
    content: 'USER_TOUR__HEADER_PREVIEW',
    title: 'USER_TOUR__HEADER_PREVIEW_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    nextOnAnchorClick: true,
  },
  {
    anchorId: TourStepAnchorEnum.PREVIEW_DIALOG_CONTENT,
    content: 'USER_TOUR__PREVIEW_DIALOG_CONTENT',
    title: 'USER_TOUR__PREVIEW_DIALOG_CONTENT_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    isAsync: true,
  },
  {
    anchorId: TourStepAnchorEnum.PREVIEW_DIALOG_CLOSE,
    content: 'USER_TOUR__PREVIEW_DIALOG_CLOSE',
    title: 'USER_TOUR__PREVIEW_DIALOG_CLOSE_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    placement: TOUR_POSITION_SETTING_BEFORE,
    nextOnAnchorClick: true,
    isAsync: true,
  },
  {
    anchorId: TourStepAnchorEnum.HEADER_DOWNLOAD,
    content: 'USER_TOUR__HEADER_DOWNLOAD',
    title: 'USER_TOUR__HEADER_DOWNLOAD_TITLE',
    stepDimensions: TOUR_WIDTH_SETTING,
    delayBeforeStepShow: TOUR_SIDEBAR_ANIMATION_DELAY,
  },
];
