export const enum BreakerSize {
  ONE = 1,
  TWO = 2,
  THREE = 3,
}

export const enum BreakerFontSizes {
  SIX = '6px',
  EIGHT = '8px',
  TEN = '10px',
  TWELVE = '12px',
  FOURTEEN = '14px',
  SIXTEEN = '16px',
  EIGHTEEN = '18px',
  TWENTY = '20px',
  TWENTY_TWO = '22px',
  TWENTY_FOUR = '24px',
  THIRTY_TWO = '32px',
  FORTY_EIGHT = '48px',
}

export const enum BreakerType {
  BREAKER = 'breaker',
}

export const enum BreakerColor {
  RED = 'red',
  LIGHT_RED = '#DD594F',
  PINK = '#CA7C76',
  DARK_PINK = '#9C6E6B',
  GREY = 'grey',
  DARK_GREEN = '#426F46',
  GREEN = '#4D8452',
  LIGHT_GREEN = '#67A457',
  SAND = '#DBA047',
  BROWN = '#B9662A',
  LIGHT_BROWN = '#CA7C21',
  DARK_BLUE = '#3250B9',
  BLUE = '#4E6CD6',
  LIGHT_BLUE = '#5171E4',
  PURPLE = '#7C4B93',
}

export const enum BreakerIcon {
  HOME = 'home',
  BATHROOM = 'bathroom',
  WASHING_MACHINE = 'local_laundry_service',
  DISHWASHER = 'dishwasher_gen',
  SOCKETS = 'electrical_services',
  LAMP = 'lightbulb',
  LAMP_CIRCLE = 'lightbulb_circle',
  LIGHT = 'light',
  BOLT = 'bolt',
  OFFLINE_BOLT = 'offline_bolt',
  POWER = 'power',
  EV_STATION = 'ev_station',
  HOUSE = 'house',
  MICROWAVE = 'microwave',
  KETTLE = 'kettle',
  OVEN_GEN = 'oven_gen',
  OVEN = 'oven',
  GARAGE_HOME = 'garage_home',
  GARAGE = 'garage',
  DINING = 'dining',
  HEAT_PUMP = 'heat_pump',
  BEDROOM_BABY = 'bedroom_baby',
  BEDROOM_PARENT = 'bedroom_parent',
  MODE_OFF_ON = 'mode_off_on',
  LIVING = 'living',
  WATER_HEATER = 'water_heater',
  AIR_PURIFIER_GEN = 'air_purifier_gen',
  AIR_PURIFIER = 'air_purifier',
  COOKING = 'cooking',
  KITCHEN = 'kitchen',
  AIRWARE = 'airware',
  SWITCH = 'switch',
  AC_UNIT = 'ac_unit',
  SKILLET_COOKTOP = 'skillet_cooktop',
  MODE_FAN = 'mode_fan',
  GATE = 'gate',
  SETTING_ALERT = 'settings_alert',
  LIGHT_GROUP = 'light_group',
  WALL_LAMP = 'wall_lamp',
  EMOJI_OBJECT = 'emoji_objects',
  WB_SUNNY = 'wb_sunny',
}
