export const enum SwitcherType {
  EU = 'eu',
  US = 'us',
}

export const enum LabelFont {
  ALEGREYA = 'Alegreya',
  ALEGREYA_SANS = 'Alegreya Sans',
  ARCHIVO_NARROW = 'Archivo Narrow',
  BIO_RHYME = 'BioRhyme',
  CARDO = 'Cardo',
  CHIVO = 'Chivo',
  CORMORANT = 'Cormorant',
  DM_SANS = 'DM Sans',
  ECZAR = 'Eczar',
  FIRA_SANS = 'Fira Sans',
  IBM_PLEX_SANS = 'IBM Plex Sans',
  INCONSOLATA = 'Inconsolata',
  INKNUT_ANTIQUA = 'Inknut Antiqua ',
  INTER = 'Inter',
  KARLA = 'Karla',
  LATO = 'Lato',
  LIBRE_BAKSERVILLE = 'Libre Bakserville',
  LIBRE_FRANKLIN = 'Libre Franklin',
  LORA = 'Lora',
  MANROPE = 'Manrope',
  MERRIWEATHER = 'Merriweather',
  MONTSERRAT = 'Montserrat',
  NEUTON = 'Neuton',
  OPEN_SANS = 'Open Sans',
  PLAYFAIR_DISPLAY = 'Playfair Display',
  POPPINS = 'Poppins',
  PROZA_LIBRE = 'Proza Libre',
  PT_SANS = 'PT Sans',
  PT_SERIF = 'PT Serif',
  RALEAY = 'Raleway',
  ROBOTO = 'Roboto',
  ROBOTO_SLAB = 'Roboto Slab',
  RUBIK = 'Rubik',
  SOURCE_SANS_PRO = 'Source Sans Pro',
  SOURCE_SERIF_PRO = 'Source Serif Pro',
  SPACE_GROTESK = 'Space Grotesk',
  SPACE_MONO = 'Space Mono',
  SPECTRAL = 'Spectral',
  SYNE = 'Syne',
  WORK_SANS = 'Work Sans',
}

export const enum LabelPosition {
  ABOVE = 'above',
  LEFT = 'left',
  RIGHT = 'right',
  UNDER = 'under',
}
